djay/covidthailand

- .github/workflows/main.yml
- README.md
- covidthailand.py
Also adds dataset for cases by area
> API uploading json files

- README.md
- covidthailand.py
aim to get medium age, and provinces.
> deaths parsing

- README.md
- covidthailand.py
generic way to create top X province type plots. e.g. provinces most increasing cases. top 5 provinces with greatest positive rate.
Groups the remaining provinces and calculates for them also.
> Top provinces

- utils_scraping.py
Fixes #70; thanks for all your help! :) 八
> don't break the build if webdav unavailable; use local files instead

- utils_scraping.py
Fixes #70 w/o side-effects? <crosses fingers hopefully>
> fix webdav handling so it still works when online as well as offline

- README.md
includes wget instructions for getting data directly from the repo
> provide an easier way to get started from partial data

- .flake8
Fixes #90, silence spurious flake8 warnings
> Add a project specific flake8 config file

- utils_pandas.py
Removed the extra zero ".0" from the axis formatter and change K to lower case k.
> Remove extra zero from fomatter #86

- covid_plot.py
> Split title and subtitle #86

- covid_plot.py
The title is not shown because it's not part of that PR. Other font sizes are shown...
> Change font sizes #86

- covid_plot.py
Removed y-axis labels and added percent formatter.
> Remove y-axis labels #86

- covid_data.py
- tests/test_scraping.py
- utils_scraping.py
- utils_scraping_tableau.py
fixes #92, used flake8 to find all unused imports and removed them.
> remove unused imports

- covid_plot.py
> Show last values for all plots

- covid_plot.py
- utils_pandas.py
fixes https://github.com/djay/covidthailand/issues/81
> Province Tables

- covid_plot.py
> Improve plot layout

- covid_plot.py
> Fix colours for actuals #39

- covid_plot.py
> Improve legends #168

- README.md
- covid_data_api.py
- covid_plot_cases.py
For Issue #38
The visualization might be improved
> Add cases by non-Thai nationality plot

- README.md
- covid_data.py
- covid_data_api.py
- covid_data_vac.py
- covid_plot_cases.py
- covid_plot_vacs.py
Addressing #198 
IHME data could be used to add other analysis later
> Add mobility/social distancing data and chart

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
target user
- vscode user
- Github Codespace user
> add devcontainer for easy dev environment setup
